### PR TITLE
Nordpool Spot price signal support

### PR DESCRIPTION
**Pull request by jpalo**
There are two things I'd like you to pay attention to and comment: resolution and API token.

**Signal specific properties**
Nordpool Spot prices are by the hour, thus the resolution of the signal is now configurable per signal, 1800 for current ones vs. 3600 for this one. Please see if that's the best way of defining it - I tried to think a bit further and make it configurable per signal as there may be other signals in the future with different resolutions. Nordpool signals also have two more properties: _currency_ and _vat_. _Currency_ is used in the HTTP GET query when fetching data, _vat_ is used when calculating the actual price.

**API Token**
There needs to be a way to persist installation specific API token for querying Nordpool Spot prices. Please see if that's the correct way to persist it (in the DB). API key never changes, is personal, and must be requested for each installation from [Expektra](http://datafeed.expektra.se/datafeed.svc/spotprice).

### CODE REVIEW

**Comment by TrystanLea** [comment]
Hello @jpalo sorry for the delay and thankyou for the pull requests. I will try and review this soon.

**Comment by jpalo** [comment]
That new multiuser functionality breaks this PR, need to figure out why...

**Comment by jpalo** [comment]
Updated changes from master.

**Comment by TrystanLea** [comment]
Hello @jpalo 

Just taking a look at this. Could you give me an example of what the nordpool signal looks like e.g the result of this request:

    http://datafeed.expektra.se/datafeed.svc/spotprice?token=$token&bidding_area=$area&format=json&perspective=$currency&$time

I want to think through this resolution question a bit and see if I think this makes sense

**Comment by jpalo** [comment]
```
<response>
<id>Electricity Spot Price</id>
<unit>EUR/MWh</unit>
<data>
<value utc="2020-05-04T17:00:00Z">27.05</value>
<value utc="2020-05-04T18:00:00Z">30.58</value>
<value utc="2020-05-04T19:00:00Z">46.26</value>
<value utc="2020-05-04T20:00:00Z">32.75</value>
<value utc="2020-05-04T21:00:00Z">18.46</value>
<value utc="2020-05-04T22:00:00Z">15.45</value>
<value utc="2020-05-04T23:00:00Z">10.12</value>
<value utc="2020-05-05T00:00:00Z">7.02</value>
<value utc="2020-05-05T01:00:00Z">7.07</value>
<value utc="2020-05-05T02:00:00Z">9.45</value>
<value utc="2020-05-05T03:00:00Z">14.5</value>
<value utc="2020-05-05T04:00:00Z">21.22</value>
<value utc="2020-05-05T05:00:00Z">28.54</value>
<value utc="2020-05-05T06:00:00Z">26.06</value>
<value utc="2020-05-05T07:00:00Z">22.35</value>
<value utc="2020-05-05T08:00:00Z">23.59</value>
<value utc="2020-05-05T09:00:00Z">22.95</value>
<value utc="2020-05-05T10:00:00Z">20.27</value>
<value utc="2020-05-05T11:00:00Z">19.1</value>
<value utc="2020-05-05T12:00:00Z">17.16</value>
<value utc="2020-05-05T13:00:00Z">16.12</value>
<value utc="2020-05-05T14:00:00Z">17.31</value>
<value utc="2020-05-05T15:00:00Z">20.42</value>
<value utc="2020-05-05T16:00:00Z">24.1</value>
<value utc="2020-05-05T17:00:00Z">22.07</value>
<value utc="2020-05-05T18:00:00Z">23.53</value>
<value utc="2020-05-05T19:00:00Z">27.34</value>
<value utc="2020-05-05T20:00:00Z">19.53</value>
<value utc="2020-05-05T21:00:00Z">6.42</value>
</data>
<details>
<bidding_area>FI</bidding_area>
<source>Nord Pool Spot</source>
<provider>Expektra</provider>
<condition>
This service may be used only by individuals and organizations in non-commercial purpose and it is not permitted to redistribute this data. Contact spotprice@expektra.com regarding other options. As of 2017-07-01 you will need an access token in order to access this service. Contact us on spotprice@expektra.com for more information about this.
</condition>
</details>
</response>
```

**Comment by TrystanLea** [comment]
Thanks @jpalo any chance for the json version?

Im working on a more modular forecast fetching implementation here that should make it easier to add more forecasts in the future.

**Comment by jpalo** [comment]
Silly me, sent the XML by mistake.

```
{
  "id": "Electricity Spot Price",
  "unit": "EUR/MWh",
  "data": [
    {
      "utc": "2020-05-22T08:00:00Z",
      "value": "37.96"
    },
    {
      "utc": "2020-05-22T09:00:00Z",
      "value": "43.62"
    },
    {
      "utc": "2020-05-22T10:00:00Z",
      "value": "38.51"
    },
    {
      "utc": "2020-05-22T11:00:00Z",
      "value": "20.18"
    },
    {
      "utc": "2020-05-22T12:00:00Z",
      "value": "11.17"
    },
    {
      "utc": "2020-05-22T13:00:00Z",
      "value": "9.98"
    },
    {
      "utc": "2020-05-22T14:00:00Z",
      "value": "9.95"
    },
    {
      "utc": "2020-05-22T15:00:00Z",
      "value": "10.11"
    },
    {
      "utc": "2020-05-22T16:00:00Z",
      "value": "21.96"
    },
    {
      "utc": "2020-05-22T17:00:00Z",
      "value": "21.62"
    },
    {
      "utc": "2020-05-22T18:00:00Z",
      "value": "9.9"
    },
    {
      "utc": "2020-05-22T19:00:00Z",
      "value": "12.41"
    },
    {
      "utc": "2020-05-22T20:00:00Z",
      "value": "15.91"
    },
    {
      "utc": "2020-05-22T21:00:00Z",
      "value": "7.25"
    }
  ],
  "details": {
    "bidding_area": "FI",
    "source": "Nord Pool Spot",
    "provider": "Expektra",
    "condition": "This service may be used only by individuals and organizations in non-commercial purpose and it is not permitted to redistribute this data. Contact spotprice@expektra.com regarding other options. As of 2017-07-01 you will need an access token in order to access this service. Contact us on spotprice@expektra.com for more information about this."
  }
}
```

**Comment by TrystanLea** [comment]
Thankyou!

**Comment by TrystanLea** [comment]
@jpalo I've sent you a private message on the forum, wondering if I can use your token to test here..

**Comment by TrystanLea** [comment]
Im still quite a way off completing this yet but I've pushed up initial work towards a more modular forecasting fetching implementation so that you can see what Im doing.

Here's the branch:
https://github.com/emoncms/demandshaper/tree/modular_forecasts

Nordpool forecast parser (you will see the layout is very similar to the other forecast parsers):
https://github.com/emoncms/demandshaper/blob/modular_forecasts/forecasts/nordpool.php

documentation page showing parsed output: https://github.com/emoncms/demandshaper/blob/modular_forecasts/docs/forecasts/nordpool.md

Solcast parser:
https://github.com/emoncms/demandshaper/blob/modular_forecasts/forecasts/solcast.php

Example of fetching forecasts using a command line script:
https://github.com/emoncms/demandshaper/blob/modular_forecasts/cli/cli_test_forecast.php

Example of scheduling using a command line script:
https://github.com/emoncms/demandshaper/blob/modular_forecasts/cli/cli_schedule.php

Example of combining multiple forecasts and then scheduling using a command line script:
https://github.com/emoncms/demandshaper/blob/modular_forecasts/cli/cli_combine_forecasts_schedule.php

A start on a UI to combine multiple forecasts, e.g grid pricing forecast with a home solar forecast

image

There's a lot more rewriting needed else where in the demandshaper module to get all of this to work but thought Id share what I have working so far :)

**Comment by TrystanLea** [comment]
I've also reworked the scheduling algorithm to make it possible to schedule periods that can be any number of seconds long. e.g 3642 seconds, it will overlap into the best half-hour or hour either side ..

**Comment by jpalo** [comment]
Looks promising. CLI "tools" will definitely streamline development and the idea of forecast weighting can be useful in many scenarios. Just need to get my head around how it should work in that solar scenario considering there are few variables there: load of the device, overall load in the phase, solar production, price of electricity. 

I mean, unless you can predict how much overall load there will be in the phase at a given time, you cannot say if it is cheaper to turn on the device at that given time - although there might be lot of solar energy forecasted - as there might be lot of other load on the phase eating all solar production meaning you end up buying 100% of that devices energy from the grid.

Maybe I'm just thinking it too complex. Anyway, I'll definitely give this a closer look. More modular way of doing this is definitely right way.

**Comment by TrystanLea** [comment]
Hello @jpalo 

I've finally managed to bring the work on modular forecasts and integration of Nordpool to a completion, its now released as v2 of the demandshaper, it would be great if you can test it to make sure it works well for what you need it to do:
https://github.com/emoncms/demandshaper/releases/tag/2.0.0

Im still working on the developer documentation, I hope to make it easier to add things from here on out.

Thanks a lot for bearing with me on this!

Trystan

**Comment by jpalo** [comment]
Nice work, looking good! 

Only one issue I've found so far is some issue related to time zones. Demandshaper shows correctly 3am to 6am, which is the lowest price in local time. However, as it seems to send UTC hours (from 1 to 4) to OpenEVSE, it becomes 1am to 4am on OpenEVSE as OpenEVSE is in local timezone. I believe it should send times to OpenEVSE as in local timezone.

I haven't yet dug deeper into the issue so I may assume something wrong, but the issue is there nevertheless.

image

**Comment by jpalo** [comment]
Also it fails to render the chart (nothing there) the next day, and no longer also allows saving signal details. Last time I fixed it by deleting the schedule redis key.

Will try to find time to investigate further.

**Comment by TrystanLea** [comment]
Thanks @jpalo I've fixed the places I can find with hardcoded timezones, I wonder if you could try again now?

I will reopen this thread so that we can keep track of the conversation for now

**Comment by jpalo** [comment]
Thanks, will test. How is it supposed to save the Signal selection? I configure it, including the nordpool api key, but it just won't save it anywhere.

**Comment by jpalo** [comment]
In fact, I suspect the demandshaper_run.php might still use some wrong timezone as it keeps going off 3 hours after a while. Opening web page once correctly sets it. Maybe there is a need for default timezone as there is no user running that scheduled run, or just use tz of the user 1?

**Comment by jpalo** [comment]
Let's close this, I'll submit fixes in another PR.

**Pull request closed without merging**
